### ISSUE TITLE
output over multiple lines

### ISSUE THREAD

**Issue by Mellbourn** [sharkdp/hyperfine#630] opened 2023-03-17 22:16 UTC
I've used hyperfine for a long time. Excellent tool. Recently it started to behave incorrectly visually. Instead of the output animating a single line, it prints several lines:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/1785727/226062310-9960a7d2-ae8f-4b40-9aa8-5fc81ea065ed.png">

This is the only program that I've noticed this sort of behaviour in.

I'm running on a Macbook with macOS Ventura 13.2.1 and zsh 5.9 (arm-apple-darwin22.1.0)

**Comment by sharkdp** [comment] 2023-03-18 09:23
Thank you for reporting this. Which version of hyperfine do you have? The latest 1.16?

**Comment by Mellbourn** [comment] 2023-03-18 09:30
Yes, 1.16.0, I upgrade my tools often, so the behavior could have started with the upgrade.

**Comment by Mellbourn** [comment] 2023-03-18 09:35
Here is a recording of the behaviour:

https://user-images.githubusercontent.com/1785727/226097613-5842d7b0-1dfc-413d-a8ce-8812ec81b474.mov

**Comment by Mellbourn** [comment] 2023-03-18 09:38
Here is a recording of the behavior:

https://user-images.githubusercontent.com/1785727/226097700-b5995b26-8db5-4bf0-9582-591d719e812e.mov

**Comment by sharkdp** [comment] 2023-03-21 19:46
> This is the only program that I've noticed this sort of behaviour in.

Just to be sure: by "the only program", you mean `zsh -is < /dev/null`, correct? When I first read the ticket I thought you meant that `hyperfine` is the only program where you saw this behavior.

I _can_ reproduce this with `hyperfine "zsh -is </dev/null"`, and I can also confirm that this is a regression in 1.16, caused by an update of the *indicatif* dependency which is responsible for drawing those progress bars.

We should probably report this upstream, but it is worth noting that `zsh -is < /dev/null` behaves extremely strange even when running this in a plain terminal. Notice the error messages and the additional prompt line with the `%` character:

![image](https://user-images.githubusercontent.com/4209276/226723825-e4303a15-8566-4cb4-90e1-2a99519504ab.png)

**Comment by sharkdp** [comment] 2023-03-21 19:59
A workaround for now is to disable the progress bars:
```
hyperfine --style=color "zsh -is </dev/null"
```

**Comment by Mellbourn** [comment] 2023-03-22 09:17
Yes, now that you mention it, the problem seems to occur only for `zsh -is < /dev/null`. I've used that command since @romkatv [recommended it for testing zsh startup times](https://www.reddit.com/r/zsh/comments/dhqw2c/comment/f3tavks/?utm_source=share&utm_medium=web2x&context=3). So it is a bit sad that the graphics no longer work for it.

Where should I direct an upstream report?

**Comment by romkatv** [comment] 2023-03-23 08:05
> We should probably report this upstream, but it is worth noting that `zsh -is < /dev/null` behaves extremely strange even when running this in a plain terminal. Notice the error messages [...]

It's not `zsh -is < /dev/null` per se that behaves strangely, it's your zsh startup files. Apparently your startup files produce errors when stdin is not a TTY. This is fixable if you care about this.

> [...] and the additional prompt line with the `%` character:

The prompt line is printed by `zsh -is` and is intended. The `%` is printed by your outer shell. You can see it by simply running `print -n hello`.

**Comment by sharkdp** [comment] 2024-11-10 20:12
Tentatively closing this. Let me know if this continues to be a problem.

**Closed by sharkdp** 2024-11-10 20:12 UTC
Labels: bug
