### ISSUE TITLE
Allow (or warn against) using equal signs in cli flags

### ISSUE THREAD

**Issue by Alphare** [sharkdp/hyperfine#287] opened 2020-05-04 11:55 UTC
Hi,

I had a weird error earlier: `Error: The following error occurred while exporting: entity not found` and figured out it was caused by my use of `--export-csv=path` instead of `--export-csv path`.

I think both variants should work, but if that's unacceptable, `hyperfine` should warn the user about their "syntax error". Equal sign works for certain flags such as `warmup`, probably by chance.

Thanks!

**Comment by sharkdp** [comment] 2020-05-10 19:26
I can not reproduce this. The `--export-csv=path` syntax is supported:
```
❯ hyperfine 'sleep 0.01'  --export-csv=test.csv
Benchmark #1: sleep 0.01
  Time (mean ± σ):      13.1 ms ±   1.0 ms    [User: 2.0 ms, System: 1.4 ms]
  Range (min … max):    10.6 ms …  15.3 ms    229 runs

❯ cat test.csv         
command,mean,stddev,median,user,system,min,max
sleep 0.01,0.013106428483864627,0.001037058345406923,0.013380727545000002,0.0019784977292576396,0.001365758668122271,0.010606941545000002,0.015306477545000002
```

The export failed due to some OS error ("entity not found") which is probably related to the `path` that you wanted to export to. Not exactly sure what that error means, but maybe the target path was on some external device / remove filesytem which was not available, or similar.

**Comment by sharkdp** [comment] 2020-05-24 15:39
@Alphare Any feedback on this? I'd like to close it.

**Comment by Alphare** [comment] 2020-05-25 12:54
@sharkdp 
Sorry, I forgot about this issue!

It looks like this is a shell expansion issue, since it only causes a problem when the path starts with `~`. I'm not sure `hyperfine` can do anything about it.

**Comment by sharkdp** [comment] 2020-05-25 13:00
> It looks like this is a shell expansion issue, since it only causes a problem when the path starts with `~`. I'm not sure `hyperfine` can do anything about it.

Yes. Never use something like `--flag=~/...`. This will never work, as your shell will not expand the `~`. If the `~` comes first (as in `--flag ~/…`), this is fine. Use `$HOME` if in doubt. This should work: `--flag=$HOME/…`.

**Closed by sharkdp** 2020-05-25 13:00 UTC
