### ISSUE TITLE
Winget workflow failed

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/hyperfine#656] opened 2023-06-03 21:49 UTC
Well, that didn't take long: https://github.com/sharkdp/hyperfine/actions/runs/5165728774/jobs/9305463989

FYI @sitiom: this is turning out exactly like I feared. If these winget pipeline continue to take up my time, I will remove them from my projects. I'm not bitter or anything, but I really have better things to do.

**Comment by sitiom** [comment] 2023-06-04 00:24
Please take a closer look. The workflow failed, but the PR was successfully created: https://github.com/microsoft/winget-pkgs/pull/108841. An issue is already open for this: https://github.com/vedantmgoyal2009/winget-releaser/issues/167. You don't need to take your time to do anything 🙂

**Comment by sharkdp** [comment] 2023-06-04 06:31
> Wait, am I seeing this right? The version tag went from https://github.com/sharkdp/hyperfine/releases/tag/v1.16.1 to https://github.com/sharkdp/hyperfine/releases/tag/v0.17.0
> 
>     *

Yeah, that's my bad - sorry.

But it looks like this is not related to the pipeline failure, as that failed again here: https://github.com/sharkdp/hyperfine/actions/runs/5167650725/jobs/9308703493

> You don't need to take your time to do anything slightly_smiling_face

Well, but I have failing pipelines in my repo.

![image](https://github.com/sharkdp/hyperfine/assets/4209276/9a2dd301-9f96-4d85-903f-c0bfe066d5e3)

Naturally, I get notifications. I look into what went wrong. I have to create a ticket like this. Write responses to posts, etc. Sure, it doesn't take a lot of my time, but I'd rather not have to do anything.

**Comment by sitiom** [comment] 2023-06-04 09:25
> Well, but I have failing pipelines in my repo.

I think the regression is caused by the latest commit: https://github.com/vedantmgoyal2009/winget-releaser/commit/3a764c84cad1a519ebf3444fab488bcccba92081. If you want a quick fix, you can point the action version to the commit before it.

**Comment by sitiom** [comment] 2023-06-05 15:35
@sharkdp The issue has now been resolved upstream. You can safely close this issue now.

**Closed** 2023-06-05 15:47 UTC
Labels: bug, packaging/tooling
