### ISSUE TITLE
win10 cargo install hyperfine fail

### ISSUE THREAD

**Issue by PaiGack** [sharkdp/hyperfine#605] opened 2023-01-15 04:06 UTC
version
```cmd
PS E:\Code\rust\advent-of-code-2022\day01> rustc --version --verbose
rustc 1.66.1 (90743e729 2023-01-10)
binary: rustc
commit-hash: 90743e7298aca107ddaa0c202a4d3604e29bfeb6
commit-date: 2023-01-10
host: x86_64-pc-windows-msvc
release: 1.66.1
LLVM version: 15.0.2
```

install log
```cmd
PS E:\Code\rust\advent-of-code-2022\day01> cargo install hyperfine
>>
    Updating `tuna` index
  Installing hyperfine v1.15.0
   Compiling autocfg v1.1.0
   Compiling winapi v0.3.9
   Compiling windows_x86_64_msvc v0.42.1
   Compiling proc-macro2 v1.0.49
   Compiling unicode-ident v1.0.6
   Compiling quote v1.0.23
   Compiling rand_core v0.4.2
   Compiling syn v1.0.107
   Compiling serde_derive v1.0.152
   Compiling autocfg v0.1.8
   Compiling rand_core v0.3.1
   Compiling serde v1.0.152
   Compiling hashbrown v0.12.3
   Compiling num-traits v0.2.15
   Compiling indexmap v1.9.2
   Compiling num-integer v0.1.45
   Compiling windows-sys v0.42.0
   Compiling num-bigint v0.2.6
   Compiling lazy_static v1.4.0
   Compiling os_str_bytes v6.4.1
   Compiling memchr v2.5.0
   Compiling clap_lex v0.2.4
   Compiling num-rational v0.2.4
   Compiling rand_chacha v0.1.1
   Compiling num-complex v0.2.4
   Compiling terminal_size v0.2.3
   Compiling rand_pcg v0.1.2
   Compiling textwrap v0.16.0
   Compiling num-iter v0.1.43
   Compiling once_cell v1.17.0
   Compiling strsim v0.10.0
   Compiling bitflags v1.3.2
   Compiling cfg-if v1.0.0
   Compiling libc v0.2.139
   Compiling getrandom v0.2.8
   Compiling winapi-util v0.1.5
   Compiling atty v0.2.14
   Compiling termcolor v1.1.3
   Compiling rand v0.6.5
   Compiling clap v3.2.23
   Compiling rand_jitter v0.1.4
   Compiling rand_os v0.1.3
   Compiling rand_core v0.6.4
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand_xorshift v0.1.1
   Compiling thiserror v1.0.38
   Compiling anyhow v1.0.68
   Compiling ppv-lite86 v0.2.17
   Compiling regex-automata v0.1.10
   Compiling regex-syntax v0.6.28
   Compiling encode_unicode v0.3.6
   Compiling rust_decimal v1.27.0
   Compiling serde_json v1.0.91
   Compiling ryu v1.0.12
   Compiling console v0.15.5
   Compiling rand_chacha v0.3.1
   Compiling num v0.2.1
   Compiling clap_complete v3.2.5
   Compiling regex v1.7.1
   Compiling thiserror-impl v1.0.38
   Compiling csv-core v0.1.10
   Compiling itoa v0.4.8
   Compiling itoa v1.0.5
   Compiling number_prefix v0.4.0
   Compiling arrayvec v0.7.2
   Compiling indicatif v0.16.2
   Compiling statistical v1.0.0
   Compiling rand v0.8.5
   Compiling hyperfine v1.15.0
   Compiling colored v2.0.0
   Compiling shell-words v1.1.0
   Compiling bstr v0.2.17
   Compiling csv v1.1.6
error[E0432]: unresolved import `winapi::um::handleapi`
 --> D:\ProgramData\Rust\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\hyperfine-1.15.0\src\timer\windows_timer.rs:9:9
  |
9 |         handleapi::CloseHandle,
  |         ^^^^^^^^^ could not find `handleapi` in `um`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `hyperfine` due to previous error
error: failed to compile `hyperfine v1.15.0`, intermediate artifacts can be found at `C:\Users\C2\AppData\Local\Temp\cargo-installnEw21E`
```

**Comment by sharkdp** [comment] 2023-01-15 06:17
This looks like a duplicate of #595 and has already been fixed on master. If you clone the repo and `cargo install --path .` from there, that should work.

**Comment by sharkdp** [comment] 2023-01-15 06:18
Alternatively, `cargo install --locked hyperfine` might work.

**Comment by PaiGack** [comment] 2023-01-15 08:48
> Alternatively, might work.`cargo install --locked hyperfine`

Thank you. This has solved the problem.

**Comment by sharkdp** [comment] 2023-01-15 13:49
I updated the instructions in the README

**Closed by sharkdp** 2023-01-15 13:49 UTC
Labels: windows, duplicate
